name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate .env file from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > ./FutbolTrading/.env

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build Docker image
        run: |
          docker build ./FutbolTrading \
            --file ./FutbolTrading/Dockerfile \
            --tag epatinov/futboltrading:latest

      - name: Push Docker image
        run: docker push epatinov/futboltrading:latest
